### PR TITLE
64% speedup in converting esri json

### PR DESCRIPTION
**Pull request by dmfenton**
I went all functional on this and was able to achieve a 64% speedup without changing inputs or outputs. I suspect there is a lot more low hanging fruit like this throughout the lib.

Here's the report from from Node-Bench

```bash
node benchmark.js                                [16:57:31]
benchmarking /Users/.../repos/koop/benchmark.js
Please be patient.
{ http_parser: '1.0',
  node: '0.10.38',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.36',
  zlib: '1.2.8',
  modules: '11',
  openssl: '1.0.1m' }
Scores: (bigger is better)

new
Raw:
 > 0.03290129611166501
 > 0.0323846908734053
 > 0.03260869565217391
 > 0.03235294117647059
Average (mean) 0.0325619059534287

old
Raw:
 > 0.011834319526627219
 > 0.011799410029498525
 > 0.011494252873563218
 > 0.011616650532429816
Average (mean) 0.011686158240529694

Winner: new
Compared with next highest (old), it's:
64.11% faster
2.79 times as fast
0.45 order(s) of magnitude faster
QUITE A BIT FASTER
```
cc @koopjs/dev

### CODE REVIEW

**Comment by jgravois** [comment]
very cool!

**Comment by ajturner** [comment]
Nice - though still begs the question why an intermediary JSON

**Comment by dmfenton** [comment]
@ajturner Are you asking why we don't just store the esri json directly?

**Comment by ngoldman** [comment]
:+1:

**Pull request merged**
