### PR TITLE
Provide method to access plugins via BaseModel. Fixes #225

### LINKED ISSUE #225: Allow provider controllers to access koop instance
Branching off from #195 for something more specific - how should provider controllers access the koop instance? For instance, if they need to access `koop.config` or plugins or anything else set in [koop/index.js](https://github.com/koopjs/koop/blob/master/index.js). For #195, I just included a reference to the koop instance in the provider's model, which the controller already has access to. Happy to do it another way if you prefer.

Let me know if you'd like a pull request on one of the providers; I just figured since it'd probably need to be done for every provider, a discussion thread would be better.

Also, if the use case here is strictly #195, feel free to merge this discussion back into that thread. I'm assuming there'd be other reasons to access the koop instance.

### PR DESCRIPTION
**Pull request by timwis**

### CODE REVIEW

**Comment by ngoldman** [comment]
Thanks for the PR @timwis! Can you please make sure tests pass? You can run tests locally by typing `npm test`. Otherwise this looks fine.

**Comment by timwis** [comment]
Hm, they work for me... travis says "no env vars set" so it may be an issue with the CI setup

screen shot 2015-08-07 at 08 14 50

**Comment by ngoldman** [comment]
Your fork is 87 commits behind `koop:master`. There have been some updates to koop since then. I think the main thing is that we're using [`standard`](https://github.com/feross/standard). Since the PR is very small I can pull it down locally, edit the commit, and merge it manually but for future PRs please make sure the branch you're forking from (head) is up to date with upstream (base). You should be able to rebase your changes without too much trouble -- the easy way to do that is `git pull --rebase upstream master` (or `git pull -r upstream master`).

**Comment by timwis** [comment]
Oh my goodness! Silly me. I'll rebase and commit now

**Comment by timwis** [comment]
There we go :)

**Comment by ngoldman** [comment]
@timwis beat you to it! Merged your commit in #229. Thanks for catching those. `standard` got updated recently so those linting errors creeped in. I'll work on getting koop-ckan up to date today.

**Pull request closed without merging**
