### PR TITLE
fix LocalDB layer ID bug

### PR DESCRIPTION
**Pull request by ngoldman**
In koop-pgcache, layer is set to 0 if it's omitted in the `select` method:
https://github.com/koopjs/koop-pgcache/blob/master/index.js#L337-L339

In LocalDB, it's not:
https://github.com/koopjs/koop/blob/5721da12eecbcf904ce75ab5e4270fd95ee4638d/lib/Local.js#L8-L11

This ends up being a problem -- if a layer ID isn't specified in options, the `Cache.get` method fails every time even though the `insert` was successful.

This PR makes LocalDB's `select` method act the same way as koop-pgcache's.

Bug found by @kneemer :raised_hands:

### CODE REVIEW

**Comment by ngoldman** [comment]
It looks like the error is more complicated than I thought. koop-pgcache and LocalDB seem to operate fairly different. Will have to investigate further.

**Comment by dmfenton** [comment]
There's really no reason for the db to know about layer indexes at all

**Comment by ngoldman** [comment]
No disagreement, but this does fix a bug with local cache not caching things in a lot of cases.

**Comment by dmfenton** [comment]
Keep in mind though, that the processing info is going to be removed in pgcache 2.0

**Comment by ngoldman** [comment]
Tracked down why that one test was failing. This will fix basic issues with local cache failing across all providers.

**Comment by ngoldman** [comment]
ping @dmfenton

**Comment by dmfenton** [comment]
Cool :+1:

**Pull request merged**
