### PR TITLE
gracefully handle malformed esri geoms

### PR DESCRIPTION
**Pull request by dmfenton**
This PR fixes a bug exhibited in trying to transform responses from this server http://sigext.cg37.fr/arcgis/rest/services/Ext/Routes_wfs/MapServer/0. I'm not sure what it's deal is with these bad geoms. But failing gracefully seems like a good idea to me nonetheless.

### CODE REVIEW

**Comment by jgravois** [comment]
whats the objectid of a bad one?  [these](http://sigext.cg37.fr/arcgis/rest/services/Ext/Routes_wfs/MapServer/0/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=*&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=pjson) all looked okay to me.

**Comment by dmfenton** [comment]
I don't know the OID, but some of the geometries are written:
```json
{"x": "null", "y": "null"}
```

**Comment by jgravois** [comment]
i don't see any in the first 1000, but i believe you.
i'll can QA and merge.

**Comment by dmfenton** [comment]
Try page 22

**Comment by jgravois** [comment]
all tests pass locally.  bonus points for your consistent use of *gracefully* in the code.  :smile:
i also would also have accepted *we no longer choke on*

**Pull request merged**
