### PR TITLE
[DNM] Uses SpatialReference for wkid2wkt translation

### PR DESCRIPTION
**Pull request by dmfenton**
This PR swaps out calling esri-proj-codes to get WKTs for [SpatialReference](https://github.com/koopjs/spatialreference). That library wraps esri-proj-codes when the code is under Esri's authority. When a code is under EPSG authority it looks for it in PostGIS spatial_ref_sys table or else calls out to http://spatialreference.org. The benefit is that we have much greater coverage over projection codes and we default to more OGC friendly strings.

It also hard codes a projection string that @peacenlove was having issues with and refactors exporter.js for a bit more sanity.

cc @ngoldman @chelm @astauffer

### CODE REVIEW

**Comment by ngoldman** [comment]
^ needs a rebase.

**Comment by dmfenton** [comment]
Marking this DNM until I decide whether to use spatialreference.org, epsg.io, or epsg-registry.org in spatialreference

**Comment by dmfenton** [comment]
Rebased

**Comment by ngoldman** [comment]
:x: tests b failin :crying_cat_face:

**Comment by dmfenton** [comment]
fixed

**Comment by ngoldman** [comment]
ty for writing tests :sob: :revolving_hearts:

**Comment by ngoldman** [comment]
oh dang should I not have merged

**Comment by ngoldman** [comment]
@dmfenton can be reverted, sorry

**Comment by dmfenton** [comment]
It's OK, lets just talk my concern over in an issue on spatialreference

**Comment by dmfenton** [comment]
The work itself is good to go

**Pull request merged**
