### PR TITLE
removing VRTs in zip files

### PR DESCRIPTION
**Pull request by dmfenton**
ping @ngoldman

### CODE REVIEW

**Comment by ngoldman** [comment]
@dmfenton looks good, why do they need to be removed?

**Comment by jgravois** [comment]
not positive what .vrt files are (vector tile thing I think) but they definitely don't belong w/ zipped up shapefiles if that's what @dmfenton is messing with.

**Comment by dmfenton** [comment]
VRTs are an artifact of the way we are using ogr2gr to handle exports. They list all the json parts that go into making large file. This is the case of the implementation leaking out to the product.

However, one thing I've noticed is that we don't seem to be reusing json to create more than one export type.

**Comment by dmfenton** [comment]
mdot_mile_markers_and__dmfenton___dc__17__http___heorb_it_dcteam___ _and_1__dani7825_dfenton-mac_____zsh_

**Comment by ngoldman** [comment]
@dmfenton alright, thanks for clarifying. lgtm :+1:

**Comment by chelm** [comment]
@dmfenton json parts should most def be re-used for all formats under a given cache key dir. Can you verify if that is not the case?

**Comment by dmfenton** [comment]
@chelm! So this function doesn't reuse JSON:
https://github.com/koopjs/koop/blob/master/lib/ExportWorker.js#L227-L229
Neither does this one: https://github.com/koopjs/koop/blob/master/lib/Exporter.js#L127-L140

What am I missing?

**Comment by chelm** [comment]
@dmfenton yeah its super confusing to say the least. In the export worker there is a check for the vrt file here: https://github.com/koopjs/koop/blob/master/lib/ExportWorker.js#L110

If the file exists then it will not create new json parts, if the vrt file does NOT exist then the `createFiles` method gets called. 

In some cases we want to force the ExportWorker to create new json partial files (options.ignore_cache). That's why inside createFiles you see is removing parts if they already exist. Basically createFiles will destroy anything that is there already. 

So if this is not working i'd look at the name and location of the VRT file that is getting created on the clean cache, and verify that a download for different formats is re-using the same VRT. Im pretty sure it is  though.

**Comment by dmfenton** [comment]
Ok, so I didn't even address the real problem in this PR. I just thought it wasn't working because I couldn't find the code.

So
- revert this PR
- new solution to ensure vrt's don't end up in zips
- centralize export logic

**Comment by chelm** [comment]
@dmfenton you can add a second exclude like this `--exclude "*.vrt"` to the zip command here:  https://github.com/koopjs/koop/blob/master/lib/Exporter.js#L366

**Comment by dmfenton** [comment]
Ah cool. The man pages were really not helpful on that parameter.

**Pull request merged**
