### PR TITLE
Convert dates to UTC dates

### PR DESCRIPTION
**Pull request by sirws**
@jgravois 

Here is the PR for koop for you to test out.

Convert dates to UTC dates so the date shows properly in ArcGIS Online
and other Esri viewers that expect UTC.

### CODE REVIEW

**Comment by jgravois** [comment]
@dmfenton ^^

**Comment by dmfenton** [comment]
@sirws can you separate this logic into a new function rather than using the same code twice?

**Comment by sirws** [comment]
Will do.

**Comment by dmfenton** [comment]
@benstoltz do you want to resurrect this branch and push it over the finish line?

**Comment by benstoltz** [comment]
@dmfenton 👍

**Pull request closed without merging**
