### PR TITLE
Fix for WKID 28992 export

### PR DESCRIPTION
**Pull request by PeaceNlove**
I get the following error (and you probably too because I think there was an issue with the Open Data portal as well)
ogr2ogr --config SHAPE_ENCODING UTF-8 -f "ESRI Shapefile" D:\Koop\data/files/621b4d21db8b45adbc0411d2c99e1224_0/c4ed366543f9585aa7ae774af38e76bc/Gemeentegrenzen2014 D:\Koop\data/files/621b4d21db8b45adbc0411d2c99e1224_0/c4ed366543f9585aa7ae774af38e76bc/Gemeentegrenzen2014.json -t_srs "PROJCS["RD_New",GEOGCS["GCS_Amersfoort",DATUM["D_Amersfoort",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Double_Stereographic"],PARAMETER["False_Easting",155000.0],PARAMETER["False_Northing",463000.0],PARAMETER["Central_Meridian",5.38763888888889],PARAMETER["Scale_Factor",0.9999079],PARAMETER["Latitude_Of_Origin",52.15616055555555],UNIT["Meter",1.0]]" -fieldmap identity -update -append -skipfailures -lco ENCODING=UTF-8
ERROR 6: No translation for Double_Stereographic to PROJ.4 format is known.
Failed to create coordinate transformation between the
following coordinate systems.  This may be because they
are not transformable, or because projection services
(PROJ.4 DLL/.so) could not be loaded.
Source:
GEOGCS["WGS 84",
    DATUM["WGS_1984",
        SPHEROID["WGS 84",6378137,298.257223563,
            AUTHORITY["EPSG","7030"]],
        AUTHORITY["EPSG","6326"]],
    PRIMEM["Greenwich",0,
        AUTHORITY["EPSG","8901"]],
    UNIT["degree",0.0174532925199433,
        AUTHORITY["EPSG","9122"]],
    AUTHORITY["EPSG","4326"]]
Target:
PROJCS["RD_New",
    GEOGCS["GCS_Amersfoort",
        DATUM["D_Amersfoort",
            SPHEROID["Bessel_1841",6377397.155,299.1528128]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Double_Stereographic"],
    PARAMETER["False_Easting",155000.0],
    PARAMETER["False_Northing",463000.0],
    PARAMETER["Central_Meridian",5.38763888888889],
    PARAMETER["Scale_Factor",0.9999079],
    PARAMETER["Latitude_Of_Origin",52.15616055555555],
    UNIT["Meter",1.0]]

I've fixed this by hardcoding the right WKID28992 string the same way it has been done for some other projections.
See https://oegeo.wordpress.com/2008/05/20/note-to-self-the-one-and-only-rd-projection-string/ for the right string. Yes, even http://spatialreference.org/ is wrong on this issue!

The other fix is for Windows, it really wants the double quotes when ogr2gor is called.

### CODE REVIEW

**Comment by dmfenton** [comment]
@PeaceNlove I'm changing up the way we get our spatial references, you might want to wait for that. See koopjs/spatialreference

**Comment by PeaceNlove** [comment]
Looks interesting, I will have a close look at how this will work out for WKID28992. As you can read in the link in my PR, there is a wrong projection string for WKID28992 and spatialreference.org and GDAL are known for having the wrong string. 

But I think the double quotes issue for Windows is an issue that should be fixed, so maybe you can have a look at that?

**Comment by dmfenton** [comment]
Which provider are you using to bring in this string? You do have the option to pass in a WKT in the spatial reference option.

I will indeed take a look at the double quotes issue.

**Comment by PeaceNlove** [comment]
The AGOL provider, the WKT string is therefore retrieved in the Exporter.js code based on the WKID of the options object.

**Comment by dmfenton** [comment]
@PeaceNlove #252 should cover both issues you were trying to fix. Please take a look.

**Comment by dmfenton** [comment]
@peacenlove I'm closing this since the fix is already in.

You'll need a different fix for the windows strings because projection WKT's have double quotes in them

**Comment by PeaceNlove** [comment]
Ok, I think writing the projection string to disk will be a solution which will work in all cases (single vs double quotes, Windows vs linux)

**Pull request closed without merging**
